CREATE TABLE AWARD
(
    pk_award VARCHAR2(38 BYTE),
    award_id varchar2(38) default sys_guid() PRIMARY KEY NOT NULL ,
    fk_baa VARCHAR2(38 BYTE),
    proposal_no VARCHAR2(30 BYTE),
    status CHAR,
    baa VARCHAR2(50 BYTE),
    topic VARCHAR2(60 BYTE),
    title VARCHAR(255 BYTE),
    typeAward VARCHAR2(50 BYTE),
    awardNumber VARCHAR2(30 BYTE),
    subtask CHAR(2 BYTE),
    alias1 VARCHAR2(20 BYTE),
    alias2 VARCHAR2(20 BYTE),
    alias3 VARCHAR2(20 BYTE),
    alias4 VARCHAR2(20 BYTE),
    colorOfMoney VARCHAR2(3),
    programElement VARCHAR2(25),
    onr VARCHAR2(12),
    dfas VARCHAR2(12),
    duns VARCHAR2(12),
    taxid VARCHAR2(20),
    cage VARCHAR2(12),
    initialAward DATE,
    popStart DATE,
    popEnd DATE,
    opt1Start DATE,
    opt1End DATE,
    opt2Start DATE,
    opt2End DATE,
    fk_terms_Conditions NUMBER,
    programYear CHAR(24),
    awardTitle VARCHAR2(255),
    institution VARCHAR2(255),
    city VARCHAR2(50),
    state VARCHAR2(5),
    thrustArea BOOLEAN,
    capabilityComponent VARCHAR2(255),
    enterprise CHAR(2),
    patronTwo VARCHAR2(4),
    patronThree CHAR(4),
    fundingEntity CHAR(3),
    cofunded             CHAR(3),
    cofundDirectorate1   CHAR(3),
    cofundDirectorate2   CHAR(3),
    congressional        BOOLEAN,
    pbd709               BOOLEAN,
    dticNumber           VARCHAR2(10),
    animalUse            BOOLEAN,
    humanUse             BOOLEAN,
    hbcu                 BOOLEAN,
    indianControlled     BOOLEAN,
    minority             BOOLEAN,
    taxonomy             VARCHAR2(200),
    nanoTechnology       BOOLEAN,
    dodPriority1 VARCHAR2(100),
    dodPriority2 VARCHAR2(100),
    dodPriority3 VARCHAR2(100),
    dateToBE DATE,
    finalReportStatus VARCHAR2(50),
    finalReportReceived VARCHAR2(50),
    OPSECApproval VARCHAR2(50),
    PARoutingNo VARCHAR2(50),
    PAApproval VARCHAR2(50),
    deleted BOOLEAN,
    deleteUser VARCHAR2(40),
    deleteDate DATE,
    modifyUser VARCHAR2(50),
    modifyDate DATE,
    createUser VARCHAR2(50 BYTE),
    createDate DATE,
    AWARD_CRTD_ID VARCHAR2(40) NOT NULL,
    AWARD_CRTD_DT DATE NOT NULL,
    AWARD_UPDT_ID VARCHAR2(40) NOT NULL,
    AWARD_UPDT_DT DATE NOT NULL
);

INSERT into "AWARD" (pk_award,
fk_baa,
proposal_no,
status,
baa,
topic,
title,
typeAward,
awardNumber,
subtask,
alias1,
alias2,
alias3,
alias4,
colorOfMoney,
programElement,
onr,
dfas,
duns,
taxid,
cage,
initialAward,
popStart,
popEnd,
opt1Start,
opt1End,
opt2Start,
opt2End,
fk_terms_Conditions,
programYear,
awardTitle,
institution,
city,
state,
thrustArea,
capabilityComponent,
enterprise,
patronTwo,
patronThree,
fundingEntity,
cofunded,
cofundDirectorate1,
cofundDirectorate2,
congressional,
pbd709,
dticNumber,
animalUse,
humanUse,
hbcu,
indianControlled,
minority,
taxonomy,
nanoTechnology,
dodPriority1,
dodPriority2,
dodPriority3,
dateToBE,
finalReportStatus,
finalReportReceived,
OPSECApproval,
PARoutingNo,
PAApproval,
deleted,
deleteUser,
deleteDate,
modifyUser,
modifyDate,
createUser,
createDate,
AWARD_CRTD_ID,
AWARD_CRTD_DT,
AWARD_UPDT_ID,
AWARD_UPDT_DT
) values (130,
NULL,
'Prop1234',
'C',
'BAA1234',
'Topic1234',
'Title1234',
'AwardType1234',
'AwardNumber1234',
'0 ',
'alias1',
'alias2',
'alias3',
'alias4',
'6.1',
'programElement1234',
'onr1234',
'dfas1234',
'duns1234',
'taxid1234',
'cage1234',
TO_DATE('2008-05-19','YYYY-MM-DD'),
TO_DATE('2008-04-23','YYYY-MM-DD'),
TO_DATE('2011-06-22','YYYY-MM-DD'),
TO_DATE('2011-06-23','YYYY-MM-DD'),
TO_DATE('2012-09-22','YYYY-MM-DD'),
NULL,
NULL,
8,
'programYear1234',
'AwardTitle1234',
'Institution1234',
'Los Angeles',
'CA',
4,
'capabilityComponent1234',
'RD',
'CX ',
'CXW ',
'BA ',
'N ',
'n/a',
'n/a',
0,
0,
NULL,
0,
0,
0,
0,
0,
'taxonomy1234',
0,
'dodPriority1',
'dodPriority2',
'dodPriority3',
NULL,
'FinalReportStatus1234',
'12/12/2012',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
'excel',
TO_DATE('2013-05-09 1:07:34','YYYY-MM-DD HH:MI:SS'),
'excel',
TO_DATE('2013-05-09 1:07:34','YYYY-MM-DD HH:MI:SS'),
'SYSTEM',
TO_DATE('01-JAN-25','DD-MON-YY'),
'SYSTEM',
TO_DATE('01-JAN-25','DD-MON-YY')
);

commit;
